#include <stdio.h>#define read(x) scanf("%d",&x)#define write(x) printf("%d\n",x)int getinput(void ){
int local[2];
  local[1] = -1;
local[0] = local[1];
  goto L_0;
L_0:;
  read(local[0]);
  if(0>local[0])goto L_1;
goto L_2;
L_1:;
  printf("I need a non-negative number: ");
L_2:;
if(0>local[0]) goto L_0;
  return local[0];
}
int main(){
int local[38];
  printf("Welcome to the United States 1040 federal income tax program.\n");
  printf("(Note: this isn't the real 1040 form. If you try to submit your\n");
  printf("taxes this way, you'll get what you deserve!\n\n");
  printf("Answer the following questions to determine what you owe.\n\n");
  printf("Total wages, salary, and tips? ");
  local[0] = getinput();
  printf("Taxable interest (such as from bank accounts)? ");
  local[1] = getinput();
  printf("Unemployment compensation, qualified state tuition, and Alaska\n");
  printf("Permanent Fund dividends? ");
  local[2] = getinput();
  local[25] = local[0] + local[1];
local[26] = local[25] + local[2];
local[3] = local[26];
  printf("Your adjusted gross income is: ");
  write(local[3]);
  printf("Enter <1> if your parents or someone else can claim you on their");
  printf(" return. \nEnter <0> otherwise: ");
  local[14] = getinput();
  if(0!=local[14])goto L_3;
goto L_4;
L_3:;
  local[27] = local[0] + 250;
local[16] = local[27];
  local[17] = 700;
  local[18] = local[17];
  if(local[18]<local[16])goto L_5;
goto L_6;
L_5:;
  local[18] = local[16];
L_6:;
  printf("Enter <1> if you are single, <0> if you are married: ");
  local[15] = getinput();
  if(0!=local[15])goto L_7;
goto L_8;
L_7:;
  local[19] = 7350;
L_8:;
  local[19] = 7350;
  local[20] = local[18];
  if(local[20]>local[19])goto L_9;
goto L_10;
L_9:;
  local[20] = local[19];
L_10:;
  local[21] = 0;
  if(local[15]==0)goto L_11;
goto L_12;
L_11:;
  printf("Enter <1> if your spouse can be claimed as a dependant, ");
  printf("enter <0> if not: ");
  local[24] = getinput();
  if(0==local[24])goto L_13;
goto L_14;
L_13:;
  local[21] = 2800;
L_14:;
L_12:;
  local[28] = local[20] + local[21];
local[22] = local[28];
  local[4] = local[22];
L_4:;
  if(0==local[14])goto L_15;
goto L_16;
L_15:;
  printf("Enter <1> if you are single, <0> if you are married: ");
  local[15] = getinput();
  if(0!=local[15])goto L_17;
goto L_18;
L_17:;
  local[4] = 12950;
L_18:;
  if(0==local[15])goto L_19;
goto L_20;
L_19:;
  local[4] = 7200;
L_20:;
L_16:;
  local[29] = local[3] - local[4];
local[5] = local[29];
  if(local[5]<0)goto L_21;
goto L_22;
L_21:;
  local[5] = 0;
L_22:;
  printf("Your taxable income is: ");
  write(local[5]);
  printf("Enter the amount of Federal income tax withheld: ");
  local[6] = getinput();
  printf("Enter <1> if you get an earned income credit (EIC); ");
  printf("enter 0 otherwise: ");
  local[23] = getinput();
  local[7] = 0;
  if(0!=local[23])goto L_23;
goto L_24;
L_23:;
  printf("OK, I'll give you a thousand dollars for your credit.\n");
  local[7] = 1000;
L_24:;
  local[30] = local[7] + local[6];
local[8] = local[30];
  printf("Your total tax payments amount to: ");
  write(local[8]);
  local[31] = local[5] * 28;
local[32] = local[31] + 50;
local[33] = local[32] / 100;
local[9] = local[33];
  printf("Your total tax liability is: ");
  write(local[9]);
  local[34] = local[8] - local[9];
local[10] = local[34];
  if(local[10]<0)goto L_25;
goto L_26;
L_25:;
  local[12] = 0;
L_26:;
  local[12] = 0;
  if(local[10]>0)goto L_27;
goto L_28;
L_27:;
  printf("Congratulations, you get a tax refund of $");
  write(local[10]);
L_28:;
  local[35] = local[9] - local[8];
local[11] = local[35];
  if(local[11]>=0)goto L_29;
goto L_30;
L_29:;
  printf("Bummer. You owe the IRS a check for $");
  write(local[11]);
L_30:;
  if(local[11]<0)goto L_31;
goto L_32;
L_31:;
  local[13] = 0;
L_32:;
  local[13] = 0;
  write(local[5]);
  write(local[8]);
  write(local[9]);
  write(local[17]);
  write(local[20]);
  write(local[19]);
  write(local[12]);
  write(local[13]);
  local[5] = local[9];
  local[7] = 0;
  local[9] = 0;
  local[36] = local[17] + local[13];
local[12] = local[36];
  local[37] = local[20] + local[19];
local[13] = local[37];
  printf("Thank you for using ez-tax.\n");
}
